[information]
name = "Luka"
description = "LUKA LUKA LUKA"
author = "idk luka"
title = "luka luka luka luka luka luka luka luka luka luka luka luka of the dev"

[[equations]]
latex = "Luka + Dev + \\Box"