export const latexExpressions = [
  `\\frac{\\sqrt{\\Box^3 + 2 \\Box + \\sin(\\Box)}}{\\int_{\\Box}^{\\Box^2} e^{-\\Box^2} \\, d\\Box}`,
  `\\sum_{n=1}^{\\infty} \\left(\\frac{\\Box^n}{n!}\\right) + \\prod_{i=1}^{\\Box} (i^2 - 1)`,
  `\\int_{-\\infty}^{\\infty} e^{-\\frac{(\\Box - \\mu)^2}{2\\sigma^2}} \\, d\\Box`,
  `\\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{\\Box}{\\sqrt{\\Box^2 + 1}}\\right)^{\\Box}`,
  `\\sqrt{\\Box} \\cdot \\frac{\\Box!}{\\prod_{i=1}^{\\Box} (i^2 + 1)} + \\int_{0}^{\\Box} \\frac{\\sin(\\Box)}{\\Box} \\, d\\Box`,
  `\\sum_{k=0}^{\\Box} \\binom{\\Box}{k} \\cos(\\pi k) + \\int_{\\Box}^{\\Box^2} \\frac{\\Box^3 + 2\\Box^2}{\\Box} \\, d\\Box`,
  `\\prod_{n=1}^{\\Box} \\left(1 + \\frac{1}{n}\\right) \\cdot \\sqrt{\\Box} - \\sum_{k=1}^{\\Box} \\frac{(-1)^k}{2k-1}`,
  `\\int_{\\Box}^{\\infty} e^{-\\frac{\\Box^2}{2}} \\cos(\\Box) \\, d\\Box + \\sum_{n=1}^{\\Box} \\frac{(-1)^n}{n}`,
  `\\lim_{{\\Box \\to 0}} \\left(1 + \\frac{\\Box}{\\sin(\\Box)}\\right)^{\\frac{\\sqrt{\\Box^2 + 1}}{\\Box^2}}`,
  `\\int_{-\\infty}^{\\Box} \\frac{e^{-\\frac{\\Box^2}{2}}}{\\sqrt{2\\pi}} \\, d\\Box - \\sum_{n=1}^{\\Box} \\frac{(-1)^n}{n!}`,
  `\\sqrt{\\frac{\\Box^2}{\\Box + 1}} + \\int_{\\Box}^{\\Box^2} \\frac{1}{\\Box + e^{-\\Box}} \\, d\\Box`,
  `\\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{1}{\\Box}\\right)^{\\Box^2} - \\sum_{n=1}^{\\Box} \\frac{1}{n}`,
  `\\prod_{n=2}^{\\Box+1} \\left(1 - \\frac{1}{n}\\right) \\cdot \\frac{\\Box!}{\\sqrt{\\Box}}`,
  `\\int_{\\Box}^{\\Box^2} \\frac{1}{1 + e^{\\Box}} \\, d\\Box + \\cos(\\Box) \\cdot \\sin(\\Box)`,
  `\\sum_{n=1}^{\\Box} \\frac{\\Box^n}{n!} \\cdot \\frac{1}{\\sqrt{\\Box}} + \\int_{0}^{\\Box} \\frac{e^{-\\Box}}{\\Box} \\, d\\Box`,
  `\\sqrt{\\Box^2 + 1} + \\int_{-\\Box}^{\\Box} \\frac{\\Box}{\\sqrt{\\Box^2 + 1}} \\, d\\Box`,
  `\\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{\\sin(\\Box)}{\\Box}\\right)^{\\Box} - \\sum_{n=1}^{\\Box} \\frac{1}{n}`,
  `\\frac{\\Box!}{\\prod_{n=1}^{\\Box} n^2} + \\int_{\\Box}^{\\Box^2} e^{\\cos(\\Box)} \\, d\\Box`,
  `\\sum_{n=1}^{\\infty} \\frac{(-1)^n}{\\sqrt{\\Box + n}} + \\frac{\\Box^2}{\\prod_{n=1}^{\\Box} n^2}`,
  `\\int_{0}^{\\Box} \\sqrt{1 - \\sin^2(\\Box)} \\, d\\Box + \\sum_{n=1}^{\\Box} \\frac{1}{n}`,
  `\\int_{\\Box}^{\\infty} e^{-\\frac{\\Box^2}{2}} \\cos(\\Box) \\, d\\Box - \\sum_{n=1}^{\\Box} \\frac{(-1)^n}{n!} + \\prod_{k=1}^{\\Box} (2k - 1)`,
  `\\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{1}{\\Box}\\right)^{\\Box^2} - \\sum_{n=1}^{\\Box} \\frac{1}{n} + \\sqrt{\\Box + 1}`,
  `\\frac{\\Box!}{\\prod_{n=1}^{\\Box} n^2} + \\int_{\\Box}^{\\Box^2} e^{\\cos(\\Box)} \\, d\\Box - \\sqrt{\\Box^3 + 2 \\Box + \\sin(\\Box)}`,
  `\\prod_{n=1}^{\\Box} \\left(1 + \\frac{1}{n^2}\\right) \\cdot \\sqrt{\\Box} - \\sum_{k=1}^{\\Box} \\frac{(-1)^k}{k^2} + \\int_{0}^{\\Box} \\sin(\\Box) \\, d\\Box`,
  `\\sum_{n=1}^{\\Box} \\frac{(-1)^n}{\\sqrt{\\Box + n}} + \\frac{\\Box^2}{\\prod_{n=1}^{\\Box} n^2} - \\int_{0}^{\\Box} \\sqrt{1 - \\sin^2(\\Box)} \\, d\\Box`,
  `\\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{\\sin(\\Box)}{\\Box}\\right)^{\\Box} - \\sum_{n=1}^{\\Box} \\frac{1}{n} + \\frac{\\sqrt{\\Box}}{\\log(\\Box)}`,
  `\\int_{0}^{\\infty} e^{-\\frac{\\Box^2}{2}} \\cos(\\Box) \\, d\\Box + \\sum_{n=1}^{\\Box} \\frac{(-1)^n}{n!} - \\frac{1}{\\sqrt{\\Box}}`,
  `\\frac{1}{\\sqrt{2\\pi}} \\int_{-\\infty}^{\\Box} e^{-\\frac{\\Box^2}{2}} \\cos(\\Box) \\, d\\Box - \\sum_{n=1}^{\\Box} \\frac{1}{2^n} + \\frac{1}{\\Box^2}`,
  `\\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{1}{\\Box}\\right)^{\\Box^2} - \\sum_{n=1}^{\\Box} \\frac{1}{n} + \\sqrt{\\Box^3 + 2 \\Box + \\sin(\\Box)}`,
  `\\prod_{n=2}^{\\Box+1} \\left(1 - \\frac{1}{n}\\right) \\cdot \\frac{\\Box!}{\\sqrt{\\Box}} - \\sum_{k=1}^{\\Box} \\frac{(-1)^k}{k} + \\int_{0}^{\\Box} e^{-\\sin(\\Box)} \\, d\\Box`,
  `\\sqrt{\\Box^2 + 1} + \\int_{-\\Box}^{\\Box} \\frac{\\Box}{\\sqrt{\\Box^2 + 1}} \\, d\\Box - \\lim_{{\\Box \\to \\infty}} \\frac{1}{\\Box} + \\frac{1}{\\Box^2}`,
  `\\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{\\sin(\\Box)}{\\Box}\\right)^{\\Box} - \\sum_{n=1}^{\\Box} \\frac{1}{n} + \\sqrt[\\Box]{\\Box!}`,
  `\\frac{\\Box!}{\\prod_{n=1}^{\\Box} n^2} + \\int_{\\Box}^{\\Box^2} e^{\\cos(\\Box)} \\, d\\Box - \\sqrt{\\Box + \\sin(\\Box)} + \\sum_{k=1}^{\\Box} \\frac{1}{2k}`,
  `\\sum_{n=1}^{\\Box} \\frac{\\Box^n}{n!} \\cdot \\frac{1}{\\sqrt{\\Box}} + \\int_{0}^{\\Box} \\frac{e^{-\\Box}}{\\Box} \\, d\\Box - \\prod_{n=1}^{\\Box} (1 + \\cos(\\Box))`,
  `\\sqrt{\\Box^2 + 1} + \\int_{-\\Box}^{\\Box} \\frac{\\Box}{\\sqrt{\\Box^2 + 1}} \\, d\\Box - \\lim_{{\\Box \\to \\infty}} \\frac{1}{\\Box} + \\frac{1}{\\Box^2}`,
  `\\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{1}{\\Box}\\right)^{\\Box^2} - \\sum_{n=1}^{\\Box} \\frac{1}{n} + \\sqrt[\\Box]{\\Box!}`,
  `\\prod_{n=2}^{\\Box+1} \\left(1 - \\frac{1}{n}\\right) \\cdot \\frac{\\Box!}{\\sqrt{\\Box}} - \\sum_{k=1}^{\\Box} \\frac{(-1)^k}{k} + \\int_{0}^{\\Box} e^{-\\sin(\\Box)} \\, d\\Box`,
  `\\sqrt{\\Box^2 + 1} + \\int_{-\\Box}^{\\Box} \\frac{\\Box}{\\sqrt{\\Box^2 + 1}} \\, d\\Box - \\lim_{{\\Box \\to \\infty}} \\frac{1}{\\Box} + \\frac{1}{\\Box^2}`,
  `\\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{\\sin(\\Box)}{\\Box}\\right)^{\\Box} - \\sum_{n=1}^{\\Box} \\frac{1}{n} + \\sqrt[\\Box]{\\Box!}`,
  `\\frac{\\Box!}{\\prod_{n=1}^{\\Box} n^2} + \\int_{\\Box}^{\\Box^2} e^{\\cos(\\Box)} \\, d\\Box - \\sqrt{\\Box + \\sin(\\Box)} + \\sum_{k=1}^{\\Box} \\frac{1}{2k}`,
  `\\int_{{-\\infty}}^{{\\infty}} e^{-\\frac{{(\\Box - \\mu)^2}}{{2\\sigma^2}}} \\, d\\Box - \\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{{\\sin(\\Box)}}{{\\Box}}\\right)^{{\\Box}} - \\sum_{{n=1}}^{{\\Box}} \\frac{{1}}{{n}} + \\frac{{1}}{{\\Box^2}} + \\sqrt{{\\frac{{\\Box^2}}{{\\Box + 1}}}}`,
  `\\prod_{{n=1}}^{{\\Box}} \\left(1 + \\frac{{1}}{{n^2}}\\right) \\cdot \\sqrt{{\\Box}} - \\sum_{{k=1}}^{{\\Box}} \\frac{{(-1)^k}}{{k^2}} + \\int_{{0}}^{{\\Box}} \\sin(\\Box) \\, d\\Box - \\frac{{1}}{{\\sqrt{2\\pi}}} \\int_{{-\\infty}}^{{\\Box}} e^{-\\frac{{\\Box^2}}{{2}}} \\cos(\\Box) \\, d\\Box + \\sum_{{n=1}}^{{\\Box}} \\frac{{1}}{{2^n}} - \\frac{{1}}{{\\Box^2}}`,
  `\\frac{{1}}{{\\sqrt{2\\pi}}} \\int_{{-\\infty}}^{{\\Box}} e^{-\\frac{{\\Box^2}}{{2}}} \\cos(\\Box) \\, d\\Box - \\sum_{{n=1}}^{{\\Box}} \\frac{{1}}{{2^n}} + \\frac{{1}}{{\\Box^2}} + \\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{{\\sin(\\Box)}}{{\\Box}}\\right)^{{\\Box}} + \\int_{{0}}^{{\\infty}} e^{-\\frac{{\\Box^2}}{{2}}} \\cos(\\Box) \\, d\\Box`,
  `\\lim_{{\\Box \\to \\infty}} \\frac{{\\sqrt{{\\Box^3 + 2 \\Box + \\sin(\\Box)}}}}{{\\int_{{\\Box}}^{{\\Box^2}} e^{-\\Box^2} \\, d\\Box}} + \\sum_{{n=1}}^{{\\infty}} \\left(\\frac{{\\Box^n}}{{n!}}\\right) + \\prod_{{i=1}}^{{\\Box}} (i^2 - 1) + \\int_{{-\\infty}}^{{\\infty}} e^{-\\frac{{(\\Box - \\mu)^2}}{{2\\sigma^2}}} \\, d\\Box + \\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{{\\Box}}{{\\sqrt{{\\Box^2 + 1}}}}\\right)^{{\\Box}}`,
  `\\sqrt{{\\Box}} \\cdot \\frac{{\\Box!}}{{\\prod_{{i=1}}^{{\\Box}} (i^2 + 1)}} + \\int_{{0}}^{{\\Box}} \\frac{{\\sin(\\Box)}}{{\\Box}} \\, d\\Box + \\sum_{{k=0}}^{{\\Box}} \\binom{{\\Box}}{{k}} \\cos(\\pi k) + \\int_{{\\Box}}^{{\\Box^2}} \\frac{{\\Box^3 + 2\\Box^2}}{{\\Box}} \\, d\\Box - \\prod_{{n=1}}^{{\\Box}} \\left(1 + \\frac{{1}}{{n}}\\right) \\cdot \\sqrt{{\\Box}}`,
  `\\int_{{\\Box}}^{{\\infty}} e^{-\\frac{{\\Box^2}}{{2}}} \\cos(\\Box) \\, d\\Box + \\sum_{{n=1}}^{{\\Box}} \\frac{{(-1)^n}}{{n}} + \\lim_{{\\Box \\to 0}} \\left(1 + \\frac{{\\Box}}{{\\sin(\\Box)}}\\right)^{{\\frac{{\\sqrt{{\\Box^2 + 1}}}}{{\\Box^2}}}} + \\int_{{-\\infty}}^{{\\Box}} \\frac{{e^{-\\frac{{\\Box^2}}{{2}}}}}{{\\sqrt{{2\\pi}}}} \\, d\\Box - \\sqrt{{\\frac{{\\Box^2}}{{\\Box + 1}}}}`,
  `\\sqrt{{\\Box + 1}} + \\int_{{-\\Box}}^{{\\Box}} \\frac{{\\Box}}{{\\sqrt{{\\Box^2 + 1}}}} \\, d\\Box + \\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{{\\sin(\\Box)}}{{\\Box}}\\right)^{{\\Box}} - \\sum_{{n=1}}^{{\\Box}} \\frac{{1}}{{n}} + \\frac{{\\Box!}}{{\\prod_{{n=1}}^{{\\Box}} n^2}} + \\int_{{\\Box}}^{{\\Box^2}} e^{{\\cos(\\Box)}} \\, d\\Box`,
  `\\frac{{\\Box!}}{{\\prod_{{n=1}}^{{\\Box}} n^2}} + \\int_{{\\Box}}^{{\\Box^2}} e^{{\\cos(\\Box)}} \\, d\\Box - \\sqrt{{\\Box + \\sin(\\Box)}} + \\sum_{{k=1}}^{{\\Box}} \\frac{{1}}{{2k}} + \\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{{\\sin(\\Box)}}{{\\Box}}\\right)^{{\\Box}} - \\sum_{{n=1}}^{{\\Box}} \\frac{{1}}{{n}} + \\sqrt[\\Box]{{\\Box!}}`,
  `\\sum_{{n=1}}^{{\\infty}} \\frac{{(-1)^n}}{{\\sqrt{{\\Box + n}}}} + \\frac{{\\Box^2}}{{\\prod_{{n=1}}^{{\\Box}} n^2}} + \\int_{{0}}^{{\\Box}} \\sqrt{1 - \\sin^2(\\Box)} \\, d\\Box + \\sum_{{n=1}}^{{\\Box}} \\frac{{1}}{{n}} + \\int_{{-\\infty}}^{{\\Box}} \\frac{{e^{-\\frac{{\\Box^2}}{{2}}}}}{{\\sqrt{{2\\pi}}}} \\, d\\Box`,
  `\\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{{1}}{{\\Box}}\\right)^{{\\Box^2}} - \\sum_{{n=1}}^{{\\Box}} \\frac{{1}}{{n}} + \\sqrt{{\\Box^3 + 2 \\Box + \\sin(\\Box)}} + \\frac{{\\sqrt{{\\Box}}}}{{\\log(\\Box)}} + \\int_{{0}}^{{\\infty}} e^{-\\frac{{\\Box^2}}{{2}}} \\cos(\\Box) \\, d\\Box`,
  `\\prod_{{n=2}}^{{\\Box+1}} \\left(1 - \\frac{{1}}{{n}}\\right) \\cdot \\frac{{\\Box!}}{{\\sqrt{{\\Box}}}} - \\sum_{{k=1}}^{{\\Box}} \\frac{{(-1)^k}}{{k}} + \\int_{{0}}^{{\\Box}} e^{-\\sin(\\Box)} \\, d\\Box + \\frac{{\\sin(\\Box)}}{{\\Box}} + \\sum_{{n=1}}^{{\\infty}} \\frac{{(-1)^n}}{{\\sqrt{{\\Box + n}}}} + \\frac{{\\Box^2}}{{\\prod_{{n=1}}^{{\\Box}} n^2}}`,
  `\\sqrt{{\\Box + 1}} + \\int_{{-\\Box}}^{{\\Box}} \\frac{{\\Box}}{{\\sqrt{{\\Box^2 + 1}}}} \\, d\\Box - \\lim_{{\\Box \\to \\infty}} \\frac{{1}}{{\\Box}} + \\frac{{1}}{{\\Box^2}} + \\lim_{{\\Box \\to \\infty}} \\left(1 + \\frac{{\\sin(\\Box)}}{{\\Box}}\\right)^{{\\Box}} + \\sqrt{{\\frac{{\\Box^2}}{{\\Box + 1}}}}`,
];